services:
  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'user'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user']
      interval: 10s
      timeout: 5s
    
  server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 127.0.0.1:5678:8080
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - postgres

volumes:
  postgres-data:
    name: discord-gate-postgres-data
